spring:
  application:
    name: jlr-user-service
  profiles:
    active: dev
  config:
    import: optional:consul:localhost:8500
  datasource:
    url: jdbc:postgresql://localhost:5432/jlr_parts
    username: postgres
    password: jlr_password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 600000
      leak-detection-threshold: 60000
      maximum-pool-size: 5
      minimum-idle: 1
      pool-name: JLRHikariPool
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: false
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.jlr.parts: DEBUG
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  jwt:
    # Replace with your generated secret from Step 1
    secret: "jsea4MCAav5YJeKQJ0lMsE8GHTsrU/RJRYAmthBaxhg="
    access-token-expiration-seconds: 900    # 15 minutes
    refresh-token-expiration-seconds: 604800 # 7 days
    issuer: jlr-user-service
    audience: jlr-parts-system
    cookie:
      name: jlr_auth_token
      domain: localhost  # Change to actual domain in production
      path: /
      http-only: true
      secure: false     # Set to true with HTTPS in production
      same-site: Lax
      max-age: 900      # Match access token expiration